### PR TITLE
Fix osm enrich does not works

### PR DESCRIPTION
**Pull request by meomancer**
hi @timlinux 
This fix the osm-enrich that does not work

### CODE REVIEW

**Comment by timlinux** [comment]
hi @meomancer 

Thanks for the patch, keep em coming! Is there any reason to have the docker override just for that one line?

**Comment by meomancer** [comment]
i will remove it @timlinux

**Comment by meomancer** [comment]
Updated @timlinux

**Comment by timlinux** [comment]
Thanks @meomancer !

**Pull request merged**
